name: CD Pipeline

on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Feature Pipeline Docker image
        run: |
          docker build -t feature_pipeline:latest -f feature_pipeline.Dockerfile .

      - name: Build Experiment Pipeline Docker image
        run: |
          docker build -t experiment_pipeline:latest -f experiment_pipeline.Dockerfile .

      - name: Set up Google Cloud credentials
        run: |
          # Save the Google Cloud JSON key to a file
          echo "${{ secrets.GOOGLE_CLOUD_KEY_JSON }}" > $HOME/gcloud-key.json
          # Set permissions for the key file
          chmod 600 $HOME/gcloud-key.json

      - name: List files in $HOME (for debugging)
        run: ls -la $HOME

      - name: Run Feature Pipeline
        env:
          GOOGLE_CLOUD_PROJECT: ${{ env.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_BUCKET: ${{ env.GOOGLE_CLOUD_BUCKET }}
        run: |
          docker run --rm \
            -v $HOME/gcloud-key.json:/root/gcloud-key.json:ro \
            -e GOOGLE_APPLICATION_CREDENTIALS=/root/gcloud-key.json \
            -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
            -e GOOGLE_CLOUD_BUCKET=$GOOGLE_CLOUD_BUCKET \
            feature_pipeline:latest      

      - name: Run Experiment Pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          GOOGLE_CLOUD_PROJECT: ${{ env.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_BUCKET: ${{ env.GOOGLE_CLOUD_BUCKET }}
        run: |
          docker run --rm \
            -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
            -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
            -e GOOGLE_CLOUD_BUCKET=$GOOGLE_CLOUD_BUCKET \
            experiment_pipeline:latest
          
        
