name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t football_match_predictor:latest -f feature_pipeline.Dockerfile .

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CLOUD_KEY_JSON }}" > $HOME/gcloud-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-key.json"

      - name: Run Feature Pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          GOOGLE_CLOUD_PROJECT: ${{ env.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_BUCKET: ${{ env.GOOGLE_CLOUD_BUCKET }}
        run: |
          docker run --rm \
            -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
            -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
            -e GOOGLE_CLOUD_BUCKET=$GOOGLE_CLOUD_BUCKET \
            football_match_predictor:latest
